// var scaleLetters = ['A', 'As', 'B', 'C', 'Cs', 'D', 'Ds', 'E', 'F', 'Fs', 'G', 'Gs'];
// var scaleObj = {};
// var scaleObjCounts = {}
// scaleLetters.forEach(function(l){
//   scaleObj[l] = {};
//   scaleObjCounts[l] = 0;
// });
// let notesStack = JSON.parse(JSON.stringify(scaleObj));
// for(n in notesStack){
//   notesStack[n].leading = JSON.parse(JSON.stringify(scaleObjCounts));
//   notesStack[n].following = JSON.parse(JSON.stringify(scaleObjCounts));
// }
// notesStack = JSON.parse(JSON.stringify(notesStack));

var notesStack = { 
  A: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  As: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  B: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  C: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  Cs: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  D: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  Ds: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  E: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  F: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  Fs: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  G: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } },
  Gs: 
   { leading: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 },
     following: 
      { A: 0,
        As: 0,
        B: 0,
        C: 0,
        Cs: 0,
        D: 0,
        Ds: 0,
        E: 0,
        F: 0,
        Fs: 0,
        G: 0,
        Gs: 0 } } };

module.exports.copySchema = function(){
  return {
    songHeader: {
      name: '',
      bpm: 0,
      timeSignature: [],
      PPQ: 0
    }, 
    notesStack: JSON.parse(JSON.stringify(notesStack))
  }
};